"""Add ICBT enrollment models

Revision ID: 614231dca3fd
Revises: f3bb2f361069
Create Date: 2026-03-28 21:55:20.599470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614231dca3fd'
down_revision: Union[str, Sequence[str], None] = 'f3bb2f361069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icbt_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['icbt_programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icbt_enrollments_program_id'), 'icbt_enrollments', ['program_id'], unique=False)
    op.create_index(op.f('ix_icbt_enrollments_user_id'), 'icbt_enrollments', ['user_id'], unique=False)
    op.create_table('icbt_module_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icbt_module_progress_module_id'), 'icbt_module_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_icbt_module_progress_user_id'), 'icbt_module_progress', ['user_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_icbt_module_progress_user_id'), table_name='icbt_module_progress')
    op.drop_index(op.f('ix_icbt_module_progress_module_id'), table_name='icbt_module_progress')
    op.drop_table('icbt_module_progress')
    op.drop_index(op.f('ix_icbt_enrollments_user_id'), table_name='icbt_enrollments')
    op.drop_index(op.f('ix_icbt_enrollments_program_id'), table_name='icbt_enrollments')
    op.drop_table('icbt_enrollments')
    # ### end Alembic commands ###
